---
title: "Untitled"
output: html_document
date: "2023-06-14"
---

```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = 'D:/04-MLDD/')
# knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_chunk$set(results = 'hold', fig.show = 'hold', fig.align = 'center')
# rm(list=ls())

```

# setup

## load packages & functions 

```{r}
source('_data/setup.R')

suppressPackageStartupMessages({
  require(randomForest)
  require(pdp)
  require(BAMMtools)
  require(pROC)
  require(PRROC)
  require(ggbeeswarm)
  require(iml)
})

label_wrap <- function(variable, value) {
  lapply(strwrap(as.character(value), width=25, simplify=FALSE), paste, collapse="\n")
}

theme_set(theme_classic() + theme(text = element_text(family = 'Segoe UI', size = 9)))

transfm <- function(df, xname) df %>% 
  mutate(x = if(grepl('log', xname)) 10^get(xname)-1 else get(xname))

# colors.hev <- scico(5, palette = 'lajolla')[2:4]
colors.hev <- scico(8, palette = 'lapaz')[c(7,5,3)]
# colors.hev <- c(
#   rgb(242,168,168, maxColorValue = 255), 
#   rgb(164,24,24, maxColorValue = 255),
#   rgb(75,13,13, maxColorValue = 255))

ctycol <- scico(7,palette='roma')[2]
saccol <- roma.colors[5]

```

## load sherlock data

```{r}
load('_results/sac_rfmodel_0.Rdata')
f.sac <- f.rf
df.pca.sac <- df.pca
df.test.sac <- df.test
obs.sac <- obs.id

load(paste0('_results/sac_iml_0.Rdata'))
ale.sac <- iml.ale
pfi.sac <- iml.importance$results

load(paste0('_results/sac_pdp_0.Rdata'))
pdp.sac <- partials

load(paste0('_results/sac_shap_0.Rdata'))
shap.sac <- shap

```

```{r}
load('_results/sac_rfmodel_2009.Rdata')
f.sac09 <- f.rf
df.pca.sac09 <- df.pca
df.test.sac09 <- df.test
obs.sac09 <- obs.id

load(paste0('_results/sac_iml_2009.Rdata'))
ale.sac09 <- iml.ale
pfi.sac09 <- iml.importance$results

load(paste0('_results/sac_pdp_2009.Rdata'))
pdp.sac09 <- partials

load(paste0('_results/sac_shap_2009.Rdata'))
shap.sac09 <- shap

```

```{r}
load('_results/county_rfmodel_0.Rdata')
f.cty <- f.rf
df.pca.cty <- df.pca
df.test.cty <- df.test
obs.cty <- obs.id

load(paste0('_results/county_iml_0.Rdata'))
ale.cty <- iml.ale
pfi.cty <- iml.importance$results

load(paste0('_results/county_pdp_0.Rdata'))
pdp.cty <- partials

load(paste0('_results/county_shap_0.Rdata'))
shap.cty <- shap

```

```{r}
load('_results/county_rfmodel_2009.Rdata')
f.cty09 <- f.rf
df.pca.cty09 <- df.pca
df.test.cty09 <- df.test
obs.cty09 <- obs.id

load(paste0('_results/county_iml_2009.Rdata'))
ale.cty09 <- iml.ale
pfi.cty09 <- iml.importance$results

load(paste0('_results/county_pdp_2009.Rdata'))
pdp.cty09 <- partials

load(paste0('_results/county_shap_2009.Rdata'))
shap.cty09 <- shap

```

```{r}
rm(f.rf, df.pca, df.test, obs.id, iml.ale, shap, partials)

```

```{r}
samp.sac <- sample(1:nrow(df.pca.sac), 500)
samp.cty <- sample(1:nrow(df.pca.cty), 500)
samp.sac09 <- sample(1:nrow(df.pca.sac09), 500)
samp.cty09 <- sample(1:nrow(df.pca.cty09), 500)
vars <- dimension$var

```
 
# 4.3) Performance Evaluation

```{r}
data.cty <- 
  predict(f.cty$finalModel, df.test.cty, type = 'prob') %>% 
  as.data.frame %>% 
  transmute(pred = yes, obs = df.test.cty$y) %>% 
  arrange(pred)
metrics.cty <- 
  foreach (i = (0:100)/100, .combine = 'rbind') %do% {
    caret::confusionMatrix(
      data = factor(ifelse(data.cty$pred > i, 'yes', 'no'), levels = c('no','yes')), 
      reference = data.cty$obs,
      positive = 'yes')$byClass %>% c(i = i)
  } %>% data.frame

pr.auc.cty <- pr.curve(
  scores.class0 = data.cty$pred, 
  weights.class0 = data.cty$obs=='yes')$auc.integral
roc.auc.cty <- roc(response = data.cty$obs=='yes', predictor = data.cty$pred)$auc %>% toNumber
stats.cty <- caret::confusionMatrix(predict(f.cty$finalModel, df.test.cty), df.test.cty$y, positive = 'yes')
stats.cty <- c(stats.cty$overall, stats.cty$byClass)

```

```{r}
data.cty09 <- 
  predict(f.cty09$finalModel, df.test.cty09, type = 'prob') %>% 
  as.data.frame %>% 
  transmute(pred = yes, obs = df.test.cty09$y) %>% 
  arrange(pred)
metrics.cty09 <- 
  foreach (i = (0:100)/100, .combine = 'rbind') %do% {
    caret::confusionMatrix(
      data = factor(ifelse(data.cty09$pred > i, 'yes', 'no'), levels = c('no','yes')), 
      reference = data.cty09$obs,
      positive = 'yes')$byClass %>% c(i = i)
  } %>% data.frame

pr.auc.cty09 <- pr.curve(
  scores.class0 = data.cty09$pred, 
  weights.class0 = data.cty09$obs=='yes')$auc.integral
roc.auc.cty09 <- roc(response = data.cty09$obs=='yes', predictor = data.cty09$pred)$auc %>% toNumber
stats.cty09 <- caret::confusionMatrix(predict(f.cty09$finalModel, df.test.cty09), df.test.cty09$y, positive = 'yes')
stats.cty09 <- c(stats.cty09$overall, stats.cty09$byClass)

```

```{r}
data.sac <- 
  predict(f.sac$finalModel, df.test.sac, type = 'prob') %>% 
  as.data.frame %>% 
  transmute(pred = yes, obs = df.test.sac$y) %>% 
  arrange(pred)
metrics.sac <- 
  foreach (i = (0:100)/100, .combine = 'rbind') %do% {
    caret::confusionMatrix(
      data = factor(ifelse(data.sac$pred > i, 'yes', 'no'), levels = c('no','yes')), 
      reference = data.sac$obs,
      positive = 'yes')$byClass %>% c(i = i)
  } %>% data.frame

pr.auc.sac <- pr.curve(
  scores.class0 = data.sac$pred, 
  weights.class0 = data.sac$obs=='yes')$auc.integral
roc.auc.sac <- roc(response = data.sac$obs=='yes', predictor = data.sac$pred)$auc %>% toNumber
stats.sac <- caret::confusionMatrix(predict(f.sac$finalModel, df.test.sac), df.test.sac$y, positive = 'yes')
stats.sac <- c(stats.sac$overall, stats.sac$byClass)

```

```{r}
data.sac09 <- 
  predict(f.sac09$finalModel, df.test.sac09, type = 'prob') %>% 
  as.data.frame %>% 
  transmute(pred = yes, obs = df.test.sac09$y) %>% 
  arrange(pred)
metrics.sac09 <- 
  foreach (i = (0:100)/100, .combine = 'rbind') %do% {
    caret::confusionMatrix(
      data = factor(ifelse(data.sac09$pred > i, 'yes', 'no'), levels = c('no','yes')), 
      reference = data.sac09$obs,
      positive = 'yes')$byClass %>% c(i = i)
  } %>% data.frame

pr.auc.sac09 <- pr.curve(
  scores.class0 = data.sac09$pred, 
  weights.class0 = data.sac09$obs=='yes')$auc.integral
roc.auc.sac09 <- roc(response = data.sac09$obs=='yes', predictor = data.sac09$pred)$auc %>% toNumber
stats.sac09 <- caret::confusionMatrix(predict(f.sac09$finalModel, df.test.sac09), df.test.sac09$y, positive = 'yes')
stats.sac09 <- c(stats.sac09$overall, stats.sac09$byClass)

```

## TABLE 2: Model performance results

```{r}
matrix(c(
  ## statewide
  sum(df.test.cty$y=='no')/nrow(df.test.cty), stats.cty['Accuracy'], 
  0.5, stats.cty['Balanced Accuracy'],
  sum(df.test.cty$y=='yes')/nrow(df.test.cty), pr.auc.cty,
  0.5, roc.auc.cty,
  ## sacramento
  sum(df.test.sac$y=='no')/nrow(df.test.sac), stats.sac['Accuracy'], 
  0.5, stats.sac['Balanced Accuracy'],
  sum(df.test.sac$y=='yes')/nrow(df.test.sac), pr.auc.sac,
  0.5, roc.auc.sac), ncol = 2) %>% 
  data.frame %>% setNames(c('Statewide', 'Sacramento')) %>% 
  mutate(Metric = c('Accuracy', 'Balanced Accuracy', 'PR-AUC', 'ROC-AUC') %>% rep(each = 2)) %>% 
  mutate(Model = c('Null', 'RF') %>% rep(4)) %>% 
  pivot_wider(names_from = Model, names_sep = '-', values_from = c(Statewide,Sacramento)) %>% 
  gt %>% 
  fmt_number(c(starts_with('State'), starts_with('Sac')), decimals = 4) %>% 
  tab_header('Model Performance Metrics')

```

```{r}
matrix(c(
  ## statewide
  sum(df.test.cty09$y=='no')/nrow(df.test.cty09), stats.cty09['Accuracy'], 
  0.5, stats.cty09['Balanced Accuracy'],
  sum(df.test.cty09$y=='yes')/nrow(df.test.cty09), pr.auc.cty09,
  0.5, roc.auc.cty09,
  ## sacramento
  sum(df.test.sac09$y=='no')/nrow(df.test.sac09), stats.sac09['Accuracy'], 
  0.5, stats.sac09['Balanced Accuracy'],
  sum(df.test.sac09$y=='yes')/nrow(df.test.sac09), pr.auc.sac09,
  0.5, roc.auc.sac09), ncol = 2) %>% 
  data.frame %>% setNames(c('Statewide', 'Sacramento')) %>% 
  mutate(Metric = c('Accuracy', 'Balanced Accuracy', 'PR-AUC', 'ROC-AUC') %>% rep(each = 2)) %>% 
  mutate(Model = c('Null', 'RF') %>% rep(4)) %>% 
  pivot_wider(names_from = Model, names_sep = '-', values_from = c(Statewide, Sacramento)) %>% 
  gt %>% 
  fmt_number(c(starts_with('State'), starts_with('Sac')), decimals = 4) %>% 
  tab_header('Model Performance Metrics')

```

## FIG 1: Calculation of model performance metrics

```{r}
rbind(
  metrics.cty %>% mutate(spat = 'Statewide', temp = 'All Years'),
  metrics.cty09 %>% mutate(spat = 'Statewide', temp = '2009--'),
  metrics.sac %>% mutate(spat = 'Sacramento', temp = 'All Years'),
  metrics.sac09 %>% mutate(spat = 'Sacramento', temp = '2009--')) %>% 
  mutate(xlab = paste(spat, temp, sep = '\n')) %>% 
  ggplot() + 
  geom_hline(
    aes(
      yintercept = sum(df.test.sac$y=='yes')/nrow(df.test.sac), 
      color = 'Sacramento', alpha = 'All Years'), 
    linetype = 'dashed', show.legend = FALSE) + 
  geom_hline(
    aes(
      yintercept = sum(df.test.cty$y=='yes')/nrow(df.test.cty), 
      color = 'Statewide', alpha = 'All Years'), 
    linetype = 'dashed', show.legend = FALSE) + 
  geom_hline(
    aes(
      yintercept = sum(df.test.sac09$y=='yes')/nrow(df.test.sac09), 
      color = 'Sacramento', alpha = '2009--'), 
    linetype = 'dashed', show.legend = FALSE) + 
  geom_hline(
    aes(
      yintercept = sum(df.test.cty09$y=='yes')/nrow(df.test.cty09), 
      color = 'Statewide', alpha = '2009--'), 
    linetype = 'dashed', show.legend = FALSE) + 
  geom_line(aes(x = Recall, y = Precision, group = xlab, color = spat, alpha = temp)) + 
  scale_x_continuous(limits = c(0,1), expand = expansion(mult = c(0,0.01))) + 
  scale_y_continuous(limits = c(0,1), expand = expansion(mult = c(0,0.01))) + 
  scale_color_manual('Spatial\nResolution', values = c(saccol, ctycol)) +
  scale_alpha_manual('Temporal\nResolution', values = c(0.4,1)) + 
  guides(
    color = guide_legend(override.aes = list(size = 1)), 
    alpha = guide_legend(override.aes = list(size = 1, alpha = c(0.25,1)))) + 
  coord_fixed(clip = 'off') + 
  theme(
    text = element_text(family = 'Segoe UI', size = 9),
    panel.grid.major = element_line(size = 0.35), 
    legend.position = 'bottom')

```

```{r}
prauc.line <- 
  rbind(
    metrics.cty %>% mutate(spat = 'Statewide', temp = 'All Years'),
    metrics.cty09 %>% mutate(spat = 'Statewide', temp = '2009--'),
    metrics.sac %>% mutate(spat = 'Sacramento', temp = 'All Years'),
    metrics.sac09 %>% mutate(spat = 'Sacramento', temp = '2009--')) %>% 
    mutate(xlab = paste(spat, temp, sep = '\n'))
prauc.null <- 
  rbind(
    c(yint = sum(df.test.sac$y=='yes')/nrow(df.test.sac), spat = 'Sacramento', temp = 'All Years'),
    c(yint = sum(df.test.cty$y=='yes')/nrow(df.test.cty), spat = 'Statewide', temp = 'All Years'),
    c(yint = sum(df.test.sac09$y=='yes')/nrow(df.test.sac09), spat = 'Sacramento', temp = '2009--'),
    c(yint = sum(df.test.cty09$y=='yes')/nrow(df.test.cty09), spat = 'Statewide', temp = '2009--')) %>% 
  data.frame %>% mutate(yint = toNumber(yint))
prauc.point <- 
  rbind(
    c(x = stats.cty['Recall'], y = stats.cty['Precision'], spat = 'Statewide', temp = 'All Years'),
    c(x = stats.sac['Recall'], y = stats.sac['Precision'], spat = 'Sacramento', temp = 'All Years'),
    c(x = stats.cty09['Recall'], y = stats.cty09['Precision'], spat = 'Statewide', temp = '2009--'),
    c(x = stats.sac09['Recall'], y = stats.sac09['Precision'], spat = 'Sacramento', temp = '2009--')) %>% 
  data.frame %>% mutate(x = toNumber(x.Recall), y = toNumber(y.Precision))
g1 <- ggplot() + 
  geom_hline(
    data = prauc.null,
    aes(yintercept = yint, color = spat, alpha = temp), 
    linetype = 'dashed', show.legend = FALSE) + 
  geom_line(
    data = prauc.line, 
    aes(x = Recall, y = Precision, group = xlab, color = spat, alpha = temp), 
    size = 0.75) + 
  geom_point(
    data = prauc.point, 
    aes(x = x, y = y, color = spat, alpha = temp),
     size = 2, show.legend = FALSE) + 
  scale_x_continuous(limits = c(0,1), expand = expansion(mult = c(0,0.01))) + 
  scale_y_continuous(limits = c(0,1), expand = expansion(mult = c(0,0.01))) + 
  scale_color_manual('Spatial\nResolution', values = c(saccol, ctycol)) +
  scale_alpha_manual('Temporal\nResolution', values = c(0.4,1)) + 
  guides(
    color = guide_legend(override.aes = list(size = 1)), 
    alpha = guide_legend(override.aes = list(size = 1, alpha = c(0.25,1)))) + 
  coord_fixed(clip = 'off') + 
  theme(
    text = element_text(family = 'Segoe UI', size = 9),
    panel.grid.major = element_line(size = 0.35), 
    legend.position = 'bottom')

rocauc.line <- 
  rbind(
    metrics.cty %>% select(1:2) %>% rbind(c(Sensitivity = 1, Specificity = 0)) %>% 
      mutate(spat = 'Statewide', temp = 'All Years'),
    metrics.cty09 %>% select(1:2) %>% rbind(c(Sensitivity = 1, Specificity = 0)) %>% 
      mutate(spat = 'Statewide', temp = '2009--'),
    metrics.sac %>% select(1:2) %>% rbind(c(Sensitivity = 1, Specificity = 0)) %>% 
      mutate(spat = 'Sacramento', temp = 'All Years'),
    metrics.sac09 %>% select(1:2) %>% rbind(c(Sensitivity = 1, Specificity = 0)) %>% 
      mutate(spat = 'Sacramento', temp = '2009--')) %>% 
    mutate(xlab = paste(spat, temp, sep = '\n'))
rocauc.point <- 
  rbind(
    c(x = stats.cty['Specificity'], y = stats.cty['Sensitivity'], spat = 'Statewide', temp = 'All Years'),
    c(x = stats.sac['Specificity'], y = stats.sac['Sensitivity'], spat = 'Sacramento', temp = 'All Years'),
    c(x = stats.cty09['Specificity'], y = stats.cty09['Sensitivity'], spat = 'Statewide', temp = '2009--'),
    c(x = stats.sac09['Specificity'], y = stats.sac09['Sensitivity'], spat = 'Sacramento', temp = '2009--')) %>% 
  data.frame %>% mutate(x = toNumber(x.Specificity), y = toNumber(y.Sensitivity))
g2 <- ggplot() + 
  geom_line(
    data = rocauc.line,
    aes(x = Specificity, y = Sensitivity, color = spat, alpha = temp), 
    size = 0.75) +
  geom_point(
    data = rocauc.point,
    aes(x = x, y = y, color = spat, alpha = temp),
    size = 2) + 
  scale_x_reverse(limits = c(1,0), expand = expansion(mult = c(0,0.01))) + 
  scale_y_continuous('Sensitivity (Recall)', limits = c(0,1), expand = expansion(mult = c(0,0.01))) + 
  geom_abline(slope = 1, intercept = 1, linetype = 'dashed') + 
  scale_color_manual('Spatial\nResolution', values = c(saccol, ctycol)) +
  scale_alpha_manual('Temporal\nResolution', values = c(0.4,1)) + 
  coord_fixed(clip = 'off') + 
  theme(
    text = element_text(family = 'Segoe UI', size = 9),
    panel.grid.major = element_line(size = 0.25), 
    legend.position = 'none')

g1 + g2 + guide_area() + 
  plot_layout(design = 'ab\ncc', heights = c(100,1), guides = 'collect') + 
  plot_annotation(tag_levels = 'a', tag_prefix = '(', tag_suffix = ')') & 
  theme(
    legend.background = element_blank(),
    plot.tag = element_text(face = 'bold'), legend.box = 'horizontal')
ggsave('_figures/fig1_performance.png', width = 6, height = 3)

```

# 5.2) Variable Importance

## FIG 2: SHAP global feature importance

```{r}
shap.plot.cty <- shap.cty %>% 
  as.data.frame %>% select(-y) %>% 
  summarize(across(everything(), ~mean(abs(.)))) %>% 
  pivot_longer(everything(), names_to = 'varnames', values_to = 'shap') %>% 
  left_join(dimension, by = c('varnames' = 'var')) %>% 
  arrange(shap) %>% 
  mutate(
    varnames = factor(varnames, levels = varnames),
    fullname = factor(fullname, levels = fullname),
    dim = factor(dim, levels = c('H','E','V')))
shap.plot.sac <- shap.sac %>% 
  as.data.frame %>% select(-y) %>% 
  summarize(across(everything(), ~mean(abs(.)))) %>% 
  pivot_longer(everything(), names_to = 'varnames', values_to = 'shap') %>% 
  left_join(dimension, by = c('varnames' = 'var')) %>% 
  arrange(shap) %>% 
  mutate(
    varnames = factor(varnames, levels = varnames),
    fullname = factor(fullname, levels = fullname),
    dim = factor(dim, levels = c('H','E','V')))

shap.plot.cty09 <- shap.cty09 %>% 
  as.data.frame %>% select(-y) %>% 
  summarize(across(everything(), ~mean(abs(.)))) %>% 
  pivot_longer(everything(), names_to = 'varnames', values_to = 'shap') %>% 
  left_join(
    dimension %>% rbind(c(dim = 'V', var = 'med_age', fullname = 'Median Structural Age')),
    by = c('varnames' = 'var')) %>% 
  arrange(shap) %>% 
  mutate(
    varnames = factor(varnames, levels = varnames),
    fullname = factor(fullname, levels = fullname),
    dim = factor(dim, levels = c('H','E','V')))
shap.plot.sac09 <- shap.sac09 %>% 
  as.data.frame %>% select(-y) %>% 
  summarize(across(everything(), ~mean(abs(.)))) %>% 
  pivot_longer(everything(), names_to = 'varnames', values_to = 'shap') %>% 
  left_join(
    dimension %>% rbind(c(dim = 'V', var = 'med_age', fullname = 'Median Structural Age')),
    by = c('varnames' = 'var')) %>% 
  arrange(shap) %>% 
  mutate(
    varnames = factor(varnames, levels = varnames),
    fullname = factor(fullname, levels = fullname),
    dim = factor(dim, levels = c('H','E','V')))

```

```{r}
shap.plot <- 
  rbind(
    shap.plot.cty %>% mutate(spat = 'Statewide', temp = 'All Years'),
    shap.plot.sac %>% mutate(spat = 'Sacramento', temp = 'All Years'),
    shap.plot.cty09 %>% mutate(spat = 'Statewide', temp = '2009--'), 
    shap.plot.sac09 %>% mutate(spat = 'Sacramento', temp = '2009--')) 

temp <- shap.plot %>% 
  group_by(spat,temp,dim,concept) %>% 
  summarize(imptce = Sum(shap)) %>% 
  group_by(spat,temp) %>% 
  mutate(imptce = imptce/sum(imptce)) %>% 
  ungroup
temp <- temp %>% 
  group_by(spat,temp,dim) %>% 
  summarize(imptce.hev = Sum(imptce)) %>% 
  mutate(dim = factor(dim, levels = c('H','E','V'))) %>% 
  arrange(rev(dim)) %>% 
  mutate(
    start = cumsum(imptce.hev), 
    end = c(0, start[-length(dim)]),
    lab = cbind(start,end) %>% apply(1,mean)) %>% 
  ungroup %>% 
  select(-start, -end) %>% 
  left_join(
    temp %>% select(spat,temp,dim,concept,imptce), 
    by = c('spat','temp','dim')) %>%
  group_by(spat,temp,dim) %>% 
  mutate(
    id = 1:length(dim),
    lab = case_when(id==1 ~ lab)) %>% 
  select(-id) %>%
  ungroup %>% 
  group_by(dim) %>% arrange(factor(concept)) %>% 
  mutate(
    conceptid = paste(dim, concept, sep = '-') %>% 
      factor(levels = rev(c(
        'H-ARchar','H-antecedent','H-modes-lsm','E-people','E-housing',
        'V-social','V-infra','V-memory')))) %>% 
  arrange(conceptid) %>% 
  mutate(xlab = paste(spat, temp, sep = '\n')) %>% 
  mutate(xlab = factor(xlab, levels = rev(levels(factor(xlab))))) %>% 
  ungroup

ggplot(temp) + 
  geom_col(
    aes(x = as.numeric(xlab), y = imptce, group = dim),
    width = 0.75, fill = 'white', color = NA) + 
  geom_col(
    aes(x = as.numeric(xlab), y = imptce, group = dim, fill = dim, alpha = conceptid),
    width = 0.75) + 
  geom_col(
    data = temp %>% 
      group_by(spat,temp,dim) %>% 
      summarize(imptce.hev = sum(imptce)) %>% 
      ungroup %>% 
      mutate(dim = factor(dim, levels = c('H','E','V'))) %>% 
      mutate(xlab = paste(spat, temp, sep = '\n')) %>% 
      mutate(xlab = factor(xlab, levels = rev(levels(factor(xlab))))),
    aes(x = as.numeric(xlab), y = imptce.hev, group = dim), 
    width = 0.75, size = 0.25, fill = NA, color = 'grey10') + 
  geom_text(
    aes(x = as.numeric(xlab), y = lab, label = percent(imptce.hev, accuracy=1)),
    family = 'Segoe UI', fontface = 'bold', size = 9/.pt) + 
  geom_text_repel(
    data = temp %>% 
      filter(spat == 'Sacramento' & temp == '2009--') %>% 
      mutate(
        start = cumsum(imptce),
        end = c(0, start[-length(concept)]),
        lab = cbind(start,end) %>% apply(1,mean)) %>% 
      mutate(concept_name = case_match(
        concept, 
        'ARchar' ~ 'AR Characteristics',
        'antecedent' ~ 'Antecedent\nConditions',
        'modes-lsm' ~ 'Climate Modes +\nLand Surface',
        'people' ~ 'Population',
        'housing' ~ 'Housing',
        'social' ~ 'Social Vulnerability',
        'infra' ~ 'Infrastructural\nVulnerability',
        'memory' ~ 'Flood Memory')),
    aes(x = as.numeric(xlab)+0.75/2, y = lab, label = concept_name),
    direction = 'y', min.segment.length = 0,
    family = 'Segoe UI', size = 8/.pt, hjust = 0, nudge_x = 0.225, lineheight = 0.8) + 
  scale_fill_manual(
    'Dimension',
    breaks = c('H','E','V'),
    labels = c('Hazard','Exposure','Vulnerability'),
    values = colors.hev) +
  scale_alpha_manual(
    'Dimension',
    values = c(1,0.8,0.6,1,0.7,1,0.7,0.4),
    guide = guide_none()) +
  scale_x_continuous(
    breaks = 1:4, labels = levels(temp$xlab), 
    expand = expansion(add = c(0.25,1.25))) + 
  scale_y_origin('SHAP Feature Importance') + 
  theme(
    legend.position = 'bottom',
    panel.grid.major.y = element_line(size = 0.25),
    axis.title.x = element_blank())
ggsave('_figures/fig2_imptce.png', width = 6, height = 4)

```

## FIG 3: temporal comparison

```{r}
shap.plot <- shap.plot %>% 
  group_by(spat, temp) %>% 
  arrange(desc(shap)) %>% 
  mutate(rank = (1:length(dim))/length(dim)) %>% 
  ungroup

```


```{r width = 6, height = 6}
plot.cty <- shap.plot %>%
  filter(spat == 'Statewide') %>% 
  select(fullname, temp, rank, dim) %>% 
  pivot_wider(names_from = temp, values_from = rank) %>% 
  filter(complete.cases(.)) %>% 
  pivot_longer(cols = unique(shap.plot$temp), names_to = 'temp', values_to = 'rank') %>% 
  group_by(temp) %>% arrange(rank) %>% 
  mutate(rankpt = (1:length(dim))/length(dim)) %>% ungroup %>%
  mutate(temp = factor(temp, levels = c('All Years', '2009--')))
g1 <- ggplot(plot.cty) +
  geom_line(aes(x = temp, y = rankpt, group = fullname, color = dim), size = 1) +
  geom_text(
    data = plot.cty %>% filter(temp == 'All Years'),
    aes(x = temp, y = rankpt, label = fullname),
    hjust = 1, nudge_x = -0.1, family = 'Segoe UI', size = 6.5/.pt) + 
  scale_y_reverse() +
  scale_x_discrete(expand = expansion(c(3,0.1)), position = 'top') +
  scale_color_manual(
    'Dimension',
    breaks = c('H','E','V'),
    labels = c('Hazard','Exposure','Vulnerability'),
    values = colors.hev) + 
  ggtitle('Feature Importance Rank:\nStatewide', subtitle = '') + 
  theme_void() +
  theme(
    text = element_text(family = 'Segoe UI', size = 9),
    axis.text.x = element_text(face = 'bold'),
    plot.title = element_text(hjust = 0.5),
    panel.grid.major.x = element_line(color = 'grey90', size = 0.25),
    legend.position = 'bottom')

plot.sac <- shap.plot %>%
  filter(spat == 'Sacramento') %>% 
  select(fullname, temp, rank, dim) %>% 
  pivot_wider(names_from = temp, values_from = rank) %>% 
  filter(complete.cases(.)) %>% 
  pivot_longer(cols = unique(shap.plot$temp), names_to = 'temp', values_to = 'rank') %>% 
  group_by(temp) %>% arrange(rank) %>% 
  mutate(rankpt = (1:length(dim))/length(dim)) %>% ungroup %>%
  mutate(temp = factor(temp, levels = c('All Years', '2009--')))
g2 <- ggplot(plot.sac) +
  geom_line(aes(x = temp, y = rankpt, group = fullname, color = dim), size = 1) +
  geom_text(
    data = plot.sac %>% filter(temp == 'All Years'),
    aes(x = temp, y = rankpt, label = fullname),
    hjust = 1, nudge_x = -0.1, family = 'Segoe UI', size = 6.5/.pt) + 
  scale_y_reverse() +
  scale_x_discrete(expand = expansion(c(3,0.25)), position = 'top') +
  scale_color_manual(
    'Dimension',
    breaks = c('H','E','V'),
    labels = c('Hazard','Exposure','Vulnerability'),
    values = colors.hev) + 
  ggtitle('Feature Importance Rank:\nSacramento', subtitle = '') + 
  theme_void() +
  theme(
    text = element_text(family = 'Segoe UI', size = 9),
    axis.text.x = element_text(face = 'bold'),
    plot.title = element_text(hjust = 0.5),
    panel.grid.major.x = element_line(color = 'grey90', size = 0.25),
    legend.position = 'bottom')

g1 + g2 + guide_area() + 
  plot_layout(design = 'ab\ncc', heights = c(10,1), guides = 'collect') + 
  plot_annotation(tag_levels = 'a', tag_prefix = '(', tag_suffix = ')') &
  theme(
    plot.tag = element_text(size = 10, face = 'bold'),
    plot.tag.position = c(0.1,0.95))
ggsave('_figures/fig3_temporalimp.png', width = 6, height = 5)

```

## FIG 4: spatial comparison

```{r width = 6, height = 6}
plot.1981 <- shap.plot %>%
  filter(temp == 'All Years') %>% 
  select(fullname, spat, rank, dim) %>% 
  pivot_wider(names_from = spat, values_from = rank) %>% 
  filter(complete.cases(.)) %>% 
  pivot_longer(cols = unique(shap.plot$spat), names_to = 'spat', values_to = 'rank') %>% 
  group_by(spat) %>% arrange(rank) %>% 
  mutate(rankpt = (1:length(dim))/length(dim)) %>% ungroup %>%
  mutate(spat = factor(spat, levels = c('Statewide', 'Sacramento')))
g1 <- ggplot(plot.1981) +
  geom_line(aes(x = spat, y = rankpt, group = fullname, color = dim), size = 1) +
  geom_text(
    data = plot.1981 %>% filter(spat == 'Statewide'),
    aes(x = spat, y = rankpt, label = fullname),
    hjust = 1, nudge_x = -0.1, family = 'Segoe UI', size = 6.5/.pt) + 
  scale_y_reverse() +
  scale_x_discrete(expand = expansion(c(3,0.1)), position = 'top') +
  scale_color_manual(
    'Dimension',
    breaks = c('H','E','V'),
    labels = c('Hazard','Exposure','Vulnerability'),
    values = colors.hev) + 
  ggtitle('Feature Importance Rank:\nAll Years', subtitle = '') + 
  theme_void() +
  theme(
    text = element_text(family = 'Segoe UI', size = 9),
    axis.text.x = element_text(face = 'bold'),
    plot.title = element_text(hjust = 0.5),
    panel.grid.major.x = element_line(color = 'grey90', size = 0.25),
    legend.position = 'bottom')

plot.2009 <- shap.plot %>%
  filter(temp == '2009--') %>% 
  select(fullname, spat, rank, dim) %>% 
  pivot_wider(names_from = spat, values_from = rank) %>% 
  filter(complete.cases(.)) %>% 
  pivot_longer(cols = unique(shap.plot$spat), names_to = 'spat', values_to = 'rank') %>% 
  group_by(spat) %>% arrange(rank) %>% 
  mutate(rankpt = (1:length(dim))/length(dim)) %>% ungroup %>%
  mutate(spat = factor(spat, levels = c('Statewide', 'Sacramento')))
g2 <- ggplot(plot.2009) +
  geom_line(aes(x = spat, y = rankpt, group = fullname, color = dim), size = 1) +
  geom_text(
    data = plot.2009 %>% filter(spat == 'Statewide'),
    aes(x = spat, y = rankpt, label = fullname),
    hjust = 1, nudge_x = -0.1, family = 'Segoe UI', size = 6.5/.pt) + 
  scale_y_reverse() +
  scale_x_discrete(expand = expansion(c(3,0.25)), position = 'top') +
  scale_color_manual(
    'Dimension',
    breaks = c('H','E','V'),
    labels = c('Hazard','Exposure','Vulnerability'),
    values = colors.hev) + 
  ggtitle('Feature Importance Rank:\n2009--', subtitle = '') + 
  theme_void() +
  theme(
    text = element_text(family = 'Segoe UI', size = 9),
    axis.text.x = element_text(face = 'bold'),
    plot.title = element_text(hjust = 0.5),
    panel.grid.major.x = element_line(color = 'grey90', size = 0.25),
    legend.position = 'bottom')

g1 + g2 + guide_area() + 
  plot_layout(design = 'ab\ncc', heights = c(10,1), guides = 'collect') +
  plot_annotation(tag_levels = 'a', tag_prefix = '(', tag_suffix = ')') &
  theme(
    plot.tag = element_text(size = 10, face = 'bold'),
    plot.tag.position = c(0.1,0.95))
ggsave('_figures/fig4_spatialimp.png', width = 6, height = 5)

```

# Variable Impact

## FIG 5: SHAP/ALE 

```{r}
## set plot parameters
ptsize <- 0.5
linesize <- 0.75
ptcol <- 'grey50'
  
ctycol <- 'black'
  
rangehaz <- c(-0.3, 0.25)
rangeexp <- c(-0.125, 0.1)
rangevuln <- c(-0.15, 0.1)

```

```{r}
gbase.sac <- ggplot() + 
    geom_hline(yintercept = 0, color = 'grey50', size = 0.25) + 
  scale_y_continuous(
    'SHAP Feature Contribution',
    labels = percent,
    sec.axis = sec_axis(~., name = 'Accumulated Local Effects', labels = percent)) +
  theme(
    text = element_text(size = 9),
    panel.grid.major.y = element_line(size = 0.25),
    axis.line.y.right = element_line(color = saccol),
    axis.ticks.y.right = element_line(color = saccol),
    axis.title.y.left = element_blank(),
    axis.title.y.right = element_blank(),
    axis.text.y.left = element_blank(),
    axis.text.y.right = element_blank())

gbase.cty <- gbase.sac + 
  theme(
    axis.line.y.right = element_line(color = ctycol),
    axis.ticks.y.right = element_line(color = ctycol))

```

```{r}
xname <- 'logprecip_total'
g1h.cty <- gbase.cty + 
  geom_point(
    data = transfm(df.pca.cty, xname) %>% slice(samp.cty) %>% 
      mutate(y = shap.cty %>% data.frame %>% slice(samp.cty) %>% pull(xname)),
    aes(x = x, y = y), size = ptsize, color = ptcol, alpha = 0.25) + 
  geom_line(
    data = ale.cty %>% 
      filter(.feature == xname) %>% 
      mutate(.borders = toNumber(.borders)) %>% 
      filter(
        .borders > quantile(df.pca.cty[,xname],0.025) &
          .borders < quantile(df.pca.cty[,xname],0.975)) %>% 
      mutate(x = ifelse(grepl('log',.feature), 10^.borders-1, .borders)),
    aes(x = x, y = .value), size = linesize) +
  labs(
    title = 'Top 3 Hazard',
    x = dimension$fullname[dimension$var==xname] %>% str_wrap(width = 20)) +
  scale_x_continuous(expand = expansion(mult = c(0.02,0.05))) + 
  coord_cartesian(ylim = rangehaz) +
  theme(
    plot.title = element_text(face = 'bold', color = '#dda077'),
    # axis.line.y.right = element_line(color = colors.hev[1]),
    # axis.ticks.y.right = element_line(color = colors.hev[1]),
    # axis.title.y.left = element_text(),
    axis.text.y.left = element_text())

xname <- 'maxivt'
g2h.cty <- gbase.cty + 
  geom_point(
    data = transfm(df.pca.cty, xname) %>% slice(samp.cty) %>% 
      mutate(y = shap.cty %>% data.frame %>% slice(samp.cty) %>% pull(xname)),
    aes(x = x, y = y), size = ptsize, color = ptcol, alpha = 0.25) + 
  geom_line(
    data = ale.cty %>% 
      filter(.feature == xname) %>% 
      mutate(.borders = toNumber(.borders)) %>% 
      filter(
        .borders > quantile(df.pca.cty[,xname],0.025) &
          .borders < quantile(df.pca.cty[,xname],0.975)) %>% 
      mutate(x = ifelse(grepl('log',.feature), 10^.borders-1, .borders)),
    aes(x = x, y = .value), size = linesize) +
  coord_cartesian(xlim = c(250,NA), ylim = rangehaz) + 
  labs(
    x = dimension$fullname[dimension$var==xname] %>% str_wrap(width = 20)) +
  scale_x_continuous(breaks = 250*(0:10), expand = expansion(mult = c(0,0.05)))


xname <- 'logprecip_lag07'
g3h.cty <- gbase.cty + 
  geom_point(
    data = transfm(df.pca.cty, xname) %>% slice(samp.cty) %>% 
      mutate(y = shap.cty %>% data.frame %>% slice(samp.cty) %>% pull(xname)),
    aes(x = x, y = y), size = ptsize, color = ptcol, alpha = 0.25) + 
  geom_line(
    data = ale.cty %>% 
      filter(.feature == xname) %>% 
      mutate(.borders = toNumber(.borders)) %>% 
      filter(
        .borders > quantile(df.pca.cty[,xname],0.025) &
          .borders < quantile(df.pca.cty[,xname],0.975)) %>% 
      mutate(x = ifelse(grepl('log',.feature), 10^.borders-1, .borders)),
    aes(x = x, y = .value), size = linesize) +
  labs(
    x = dimension$fullname[dimension$var==xname] %>% str_wrap(width = 20)) +
  scale_x_continuous(expand = expansion(mult = c(0.02,0.05))) + 
  coord_cartesian(xlim = c(0,200), ylim = rangehaz) +
  theme(
    # axis.line.y.right = element_line(color = colors.hev[1]),
    # axis.ticks.y.right = element_line(color = colors.hev[1]),
    # axis.title.y.right = element_text(color = ctycol),
    axis.text.y.right = element_text())

```

```{r}
xname <- 'loghu'
g1e.cty <- gbase.cty + 
  geom_point(
    data = transfm(df.pca.cty, xname) %>% slice(samp.cty) %>% 
      mutate(y = shap.cty %>% data.frame %>% slice(samp.cty) %>% pull(xname)),
    aes(x = x, y = y), size = ptsize, color = ptcol, alpha = 0.25) + 
  geom_line(
    data = ale.cty %>% 
      filter(.feature == xname) %>% 
      mutate(.borders = toNumber(.borders)) %>% 
      filter(
        .borders > quantile(df.pca.cty[,xname],0.025) &
          .borders < quantile(df.pca.cty[,xname],0.975)) %>% 
      mutate(x = ifelse(grepl('log',.feature), 10^.borders-1, .borders)),
    aes(x = x, y = .value), size = linesize) +
  labs(
    title = 'Top 3 Exposure',
    x = dimension$fullname[dimension$var==xname] %>% str_wrap(width = 20)) +
  scale_x_log10() + annotation_logticks(sides = 'b', size = 0.25, color = 'grey25') + 
  coord_cartesian(ylim = rangeexp) + 
  theme(
    plot.title = element_text(face = 'bold', color = '#71938f'),
    # axis.line.y.right = element_line(color = colors.hev[2]),
    # axis.ticks.y.right = element_line(color = colors.hev[2]),
    axis.title.y.left = element_text(),
    axis.text.y.left = element_text())

xname <- 'pop_pct_floodplain'
g2e.cty <- gbase.cty + 
  geom_point(
    data = transfm(df.pca.cty, xname) %>% slice(samp.cty) %>% 
      mutate(y = shap.cty %>% data.frame %>% slice(samp.cty) %>% pull(xname)),
    aes(x = x, y = y), size = ptsize, color = ptcol, alpha = 0.25) + 
  geom_line(
    data = ale.cty %>% 
      filter(.feature == xname) %>% 
      mutate(.borders = toNumber(.borders)) %>% 
      filter(
        .borders > quantile(df.pca.cty[,xname],0.025) &
          .borders < quantile(df.pca.cty[,xname],0.975)) %>% 
      mutate(x = ifelse(grepl('log',.feature), 10^.borders-1, .borders)),
    aes(x = x, y = .value), size = linesize) +
  labs(
    x = dimension$fullname[dimension$var==xname] %>% str_wrap(width = 20)) +
  scale_x_continuous(labels = percent, expand = expansion(mult = c(0.02,0.05))) + 
  coord_cartesian(xlim = c(0,0.4), ylim = rangeexp)

xname <- 'pct_sfh'
g3e.cty <- gbase.cty + 
  geom_point(
    data = transfm(df.pca.cty, xname) %>% slice(samp.cty) %>% 
      mutate(y = shap.cty %>% data.frame %>% slice(samp.cty) %>% pull(xname)),
    aes(x = x, y = y), size = ptsize, color = ptcol, alpha = 0.25) + 
  geom_line(
    data = ale.cty %>% 
      filter(.feature == xname) %>% 
      mutate(.borders = toNumber(.borders)) %>% 
      filter(
        .borders > quantile(df.pca.cty[,xname],0.025) &
          .borders < quantile(df.pca.cty[,xname],0.975)) %>% 
      mutate(x = ifelse(grepl('log',.feature), 10^.borders-1, .borders)),
    aes(x = x, y = .value), size = linesize) +
  labs(
    x = dimension$fullname[dimension$var==xname] %>% str_wrap(width = 24)) +
  scale_x_continuous(labels = percent, expand = expansion(mult = 0.05)) + 
  coord_cartesian(xlim = c(0.4,NA), ylim = rangeexp) + 
  theme(
    # axis.line.y.right = element_line(color = colors.hev[2]),
    # axis.ticks.y.right = element_line(color = colors.hev[2]),
    axis.title.y.right = element_text(),
    axis.text.y.right = element_text())

```

```{r}
xname <- 'CRS'
g1v.cty <- gbase.cty + 
  geom_point(
    data = transfm(df.pca.cty, xname) %>% slice(samp.cty) %>% 
      mutate(y = shap.cty %>% data.frame %>% slice(samp.cty) %>% pull(xname)),
    aes(x = jitter(x), y = y), size = ptsize, color = ptcol, alpha = 0.25) + 
  geom_line(
    data = ale.cty %>% 
      filter(.feature == xname) %>% 
      mutate(.borders = toNumber(.borders)) %>% 
      filter(.borders > 2) %>% 
      mutate(x = ifelse(grepl('log',.feature), 10^.borders-1, .borders)),
    aes(x = x, y = .value), size = linesize) +
  labs(
    title = 'Top 3 Vulnerability',
    x = dimension$fullname[dimension$var==xname] %>% str_wrap(width = 20)) +
  coord_cartesian(ylim = rangevuln) +
  scale_x_continuous(breaks = 2:10) + 
  theme(
    plot.title = element_text(face = 'bold', color = colors.hev[3]),
    # axis.line.y.right = element_line(color = colors.hev[3]),
    # axis.ticks.y.right = element_line(color = colors.hev[3]),
    # axis.title.y.left = element_text(),
    axis.text.y.left = element_text())

xname <- 'pct_dac'
g2v.cty <- gbase.cty + 
  geom_point(
    data = transfm(df.pca.cty, xname) %>% slice(samp.cty) %>% 
      mutate(y = shap.cty %>% data.frame %>% slice(samp.cty) %>% pull(xname)),
    aes(x = x, y = y), size = ptsize, color = ptcol, alpha = 0.25) + 
  geom_line(
    data = ale.cty %>% 
      filter(.feature == xname) %>% 
      mutate(.borders = toNumber(.borders)) %>% 
      filter(
        .borders > quantile(df.pca.cty[,xname],0.025) &
          .borders < quantile(df.pca.cty[,xname],0.975)) %>% 
      mutate(x = ifelse(grepl('log',.feature), 10^.borders-1, .borders)),
    aes(x = x, y = .value), size = linesize) +
  labs(
    x = dimension$fullname[dimension$var==xname] %>% str_wrap(width = 20)) +
  scale_x_continuous(labels = percent, expand = expansion(0.02)) + 
  coord_cartesian(ylim = rangevuln)

xname <- 'hhincome22'
g3v.cty <- gbase.cty + 
  geom_point(
    data = transfm(df.pca.cty, xname) %>% slice(samp.cty) %>% 
      mutate(y = shap.cty %>% data.frame %>% slice(samp.cty) %>% pull(xname)),
    aes(x = x, y = y), size = ptsize, color = ptcol, alpha = 0.25) + 
  geom_line(
    data = ale.cty %>% 
      filter(.feature == xname) %>% 
      mutate(.borders = toNumber(.borders)) %>% 
      filter(
        .borders > quantile(df.pca.cty[,xname],0.025) &
          .borders < quantile(df.pca.cty[,xname],0.975)) %>% 
      mutate(x = ifelse(grepl('log',.feature), 10^.borders-1, .borders)),
    aes(x = x, y = .value), size = linesize) +
  labs(
    x = dimension$fullname[dimension$var==xname] %>% str_wrap(width = 20)) +
  scale_x_continuous(labels = comma_format(scale = 1e-3, prefix = '$', suffix = 'K')) + 
  coord_cartesian(ylim = rangevuln) +
  theme(
    # axis.line.y.right = element_line(color = colors.hev[3]),
    # axis.ticks.y.right = element_line(color = colors.hev[3]),
    # axis.title.y.right = element_text(color = ctycol),
    axis.text.y.right = element_text())

```

```{r fig.width=6, fig.height=6}
g1h.cty + g2h.cty + g3h.cty +
  g1e.cty + g2e.cty + g3e.cty + 
  g1v.cty + g2v.cty + g3v.cty + 
  plot_layout(nrow = 3) +
  plot_annotation(tag_levels = 'a', tag_prefix = '(', tag_suffix = ')') &
  theme(
    legend.position = 'none',
    plot.tag = element_text(face = 'bold'),
    plot.tag.position = c(0.12,0.975)) #1.01 without the title
ggsave('_figures/fig5_impact.png', width = 6, height = 6)

```

