---
title: "Untitled"
output: html_document
date: "2023-04-20"
---

## antecedent conditions

### NWS WWA

```{r include = FALSE, eval = FALSE}
## download WWAs 

# https://mesonet.agron.iastate.edu/request/gis/watchwarn.phtml
# https://github.com/akrherz/pyIEM/blob/main/src/pyiem/nws/vtec.py

# events <- c('WS','SV','FF','FA','FL','WI','WW')  # matches previous work
# sf::sf_use_s2(FALSE)

# wwa <- map_dfr(
#   .x = 1986:2021,
#   .f = function(yr) {
#     paste0('C:/Users/cbowers/Downloads/wwa/wwa_', yr, '01010000_', yr, '12312359.shp') %>%
#       st_read(quiet = TRUE) %>%
#       st_transform(st_crs(wus)) %>%
#       .[wus %>% filter(STUSPS == 'CA'),] %>%
#       transmute(
#         issued = ymd_hm(ISSUED),
#         expired = ymd_hm(EXPIRED),
#         phenom = PHENOM,
#         vtec = factor(case_when(
#           SIG=='W' ~ 'warning',
#           SIG=='Y' ~ 'advisory',
#           SIG=='A' ~ 'watch',
#           TRUE ~ 'other'))) %>%
#       filter(phenom %in% events) %>%
#       filter(vtec != 'other') %>%
#       mutate(year = yr)
#   })
# ## takes about twenty minutes to create this object

```

```{r include = FALSE, eval = FALSE}
# polys.temp <- polys %>% 
#   st_transform(projected) %>% 
#   mutate(totalarea = as.numeric(st_area(.))) %>% 
#   st_transform(st_crs(wwa))
# wwa <- wwa %>% mutate(wwa.id = 1:nrow(.))
# 
# timer <- Sys.time()
# pb <- txtProgressBar(min = 0, max = nrow(wwa), style = 3)
# cl <- makeCluster(cores)
# registerDoSNOW(cl)
# wwa_polys <-
#   foreach(
#     i = 1:nrow(wwa),
#     .packages = c('sf', 'raster', 'lubridate', 'dplyr'),
#     .inorder = FALSE,
#     .options.snow = opts,
#     .combine = 'rbind') %dopar% {
#       cover.id <- tryCatch( 
#         st_intersection(polys.temp, wwa[i,]) %>% 
#           st_make_valid %>%
#           mutate(partarea = as.numeric(st_area(.))) %>% 
#           mutate(pct = partarea/totalarea) %>% 
#           filter(pct > cover.threshold) %>% 
#           pull(id),
#         error = function(e) NULL)
#       if (length(cover.id) > 0) {
#         date_ids <- which(TS %within% interval(wwa$issued[i], wwa$expired[i]))
#         expand.grid(
#           id = cover.id,
#           wwa.id = wwa$wwa.id[i],
#           ts = TS[date_ids],
#           phenom = wwa$phenom[i],
#           vtec = paste(wwa$vtec[i]))
#       } else NULL
#     }
# stopCluster(cl)
# Sys.time() - timer
# ## takes 2-3 hours to create this object (california polygons)

```

```{r include = FALSE, eval = FALSE}
## checkpoint
# save(wwa, wwa_polys, file = 'D:/6-MLDD/_data/_checkpoints/wwa_ca_0412.Rdata')
load('_data/_checkpoints/wwa_ca_0412.Rdata')

```

```{r include = FALSE, eval = FALSE}
catalogs <- 
  foreach (j = 1:nrow(polys)) %do% {
    if (progressbar) setTxtProgressBar(pb,j)
    wwa_polys %>% 
      filter(id == j) %>% 
      group_by(date = as.Date(ts)) %>% 
      summarize(n = 1) %>% 
      right_join(data.frame(date = unique(as.Date(TS))), by = 'date') %>% 
      arrange(date) %>%  
      mutate(n = case_when(n == 1 ~ 1, wateryear(date) > 1986 ~ 0)) %>% 
      group_by(wy = wateryear(date)) %>% 
      mutate(nn = cumsum(n)) %>% 
      ungroup %>% 
      right_join(data.frame(date = as.Date(TS), ts = TS), by = 'date') %>% 
      transmute(start = ts, wwa = nn) %>% 
      left_join(catalogs[[j]], ., by = 'start') %>% 
      select(-id)
  }

```

