---
title: "Untitled"
output: html_document
date: "2023-04-26"
---

```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = 'D:/6-MLDD/')
# knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_chunk$set(results = 'hold', fig.show = 'hold', fig.align = 'center')
# rm(list=ls())

```

# setup

## load functions & packages

```{r}
source('_data/setup.R')

```

## load data

### county-level 

```{r}
load('_data/_checkpoints/county_catalog_0426.Rdata')
df <- catalog.df %>% 
  mutate(y = factor(ifelse(claims_num > 0, 'yes', 'no')))

## impute missing precipitation & sm lags by linear regression
f07 <- lm(logprecip_lag07 ~ logprecip_lag03 + sm_lag03, data = df)
df$logprecip_lag07[is.na(df$logprecip_lag07)] <- 
  predict(f07, df %>% filter(is.na(logprecip_lag07))) %>% 
  cbind(df$logprecip_lag03[is.na(df$logprecip_lag07)]) %>% 
  apply(1,max)
f07 <- lm(sm_lag07 ~ logprecip_lag03 + sm_lag03, data = df)
df$sm_lag07[is.na(df$sm_lag07)] <- predict(f07, df %>% filter(is.na(sm_lag07)))

f14 <- lm(logprecip_lag14 ~ logprecip_lag07 + sm_lag07 + logprecip_lag03 + sm_lag03, data = df)
df$logprecip_lag14[is.na(df$logprecip_lag14)] <- 
  predict(f14, df %>% filter(is.na(logprecip_lag14))) %>% 
  cbind(df$logprecip_lag07[is.na(df$logprecip_lag14)]) %>% 
  apply(1,max)
f14 <- lm(sm_lag14 ~ logprecip_lag07 + sm_lag07 + logprecip_lag03 + sm_lag03, data = df)
df$sm_lag14[is.na(df$sm_lag14)] <- predict(f14, df %>% filter(is.na(sm_lag14)))

f30 <- lm(logprecip_lag30 ~ logprecip_lag14 + sm_lag14 + logprecip_lag07 + sm_lag07 + logprecip_lag03, data = df)
df$logprecip_lag30[is.na(df$logprecip_lag30)] <- 
  predict(f30, df %>% filter(is.na(logprecip_lag30))) %>% 
  cbind(df$logprecip_lag14[is.na(df$logprecip_lag30)]) %>% 
  apply(1,max)
f30 <- lm(sm_lag30 ~ logprecip_lag14 + sm_lag14 + logprecip_lag07 + sm_lag07 + sm_lag03, data = df)
df$sm_lag30[is.na(df$sm_lag30)] <- predict(f30, df %>% filter(is.na(sm_lag30)))

df.county <- df

```

### tract-level 

```{r}
load('_data/_checkpoints/sac_catalog_0426.Rdata')
df <- catalog.df %>% 
  mutate(y = factor(ifelse(claims_num > 0, 'yes', 'no')))

## impute missing precipitation & sm lags by linear regression
f07 <- lm(logprecip_lag07 ~ logprecip_lag03 + sm_lag03, data = df)
df$logprecip_lag07[is.na(df$logprecip_lag07)] <- 
  predict(f07, df %>% filter(is.na(logprecip_lag07))) %>% 
  cbind(df$logprecip_lag03[is.na(df$logprecip_lag07)]) %>% 
  apply(1,max)
f07 <- lm(sm_lag07 ~ logprecip_lag03 + sm_lag03, data = df)
df$sm_lag07[is.na(df$sm_lag07)] <- predict(f07, df %>% filter(is.na(sm_lag07)))

f14 <- lm(logprecip_lag14 ~ logprecip_lag07 + sm_lag07 + logprecip_lag03 + sm_lag03, data = df)
df$logprecip_lag14[is.na(df$logprecip_lag14)] <- 
  predict(f14, df %>% filter(is.na(logprecip_lag14))) %>% 
  cbind(df$logprecip_lag07[is.na(df$logprecip_lag14)]) %>% 
  apply(1,max)
f14 <- lm(sm_lag14 ~ logprecip_lag07 + sm_lag07 + logprecip_lag03 + sm_lag03, data = df)
df$sm_lag14[is.na(df$sm_lag14)] <- predict(f14, df %>% filter(is.na(sm_lag14)))

f30 <- lm(logprecip_lag30 ~ logprecip_lag14 + sm_lag14 + logprecip_lag07 + sm_lag07 + logprecip_lag03, data = df)
df$logprecip_lag30[is.na(df$logprecip_lag30)] <- 
  predict(f30, df %>% filter(is.na(logprecip_lag30))) %>% 
  cbind(df$logprecip_lag14[is.na(df$logprecip_lag30)]) %>% 
  apply(1,max)
f30 <- lm(sm_lag30 ~ logprecip_lag14 + sm_lag14 + logprecip_lag07 + sm_lag07 + sm_lag03, data = df)
df$sm_lag30[is.na(df$sm_lag30)] <- predict(f30, df %>% filter(is.na(sm_lag30)))

df.tract <- df

```

### confirm 

```{r}
apply(df.county, 2, sum.na) %>% sum
apply(df.tract, 2, sum.na) %>% sum

```

# compare histograms

```{r}
df.county <- df.county %>% 
  select(-count, -start, -end, -id, -claims_num, -claims_value)
df.tract <- df.tract %>% 
  select(-count, -start, -end, -id, -claims_num, -claims_value)

vars <- names(df.county) %>% .[which(.!='y')]

```

```{r}
g.county <- list() 
g.tract <- list()
for (i in 1:length(vars)) {
  g.county[[i]] <- 
    ggplot(df.county %>% select(vars[i]) %>% setNames('x')) + 
    geom_histogram(aes(x=x), bins = sqrt(nrow(df.county))/5) + 
    scale_y_origin() + 
    labs(x = vars[i]) + 
    theme(axis.title.y = element_blank())
  g.tract[[i]] <- 
    ggplot(df.tract %>% select(vars[i]) %>% setNames('x')) + 
    geom_histogram(aes(x=x), bins = sqrt(nrow(df.tract))/5) + 
    scale_y_origin() + 
    labs(x = vars[i]) + 
    theme(axis.title.y = element_blank())
}
wrap_plots(g.county)
ggsave('_figures/hist_dfcounty.png', width = 15, height = 15)
wrap_plots(g.tract)
ggsave('_figures/hist_dftract.png', width = 15, height = 15)

```

# compare correlation plots

```{r}
cor(df.county %>% select(vars)) %>% 
  as.data.frame %>% 
  rownames_to_column %>% 
  pivot_longer(-rowname) %>%
  mutate(rowname = factor(rowname, levels = vars), name = factor(name, levels = rev(vars))) %>% 
  ggplot() + 
  geom_tile(aes(x = rowname, y = name, fill = value)) + 
  scale_fill_scico(palette = 'vik', midpoint = 0, direction = -1) + 
  scale_x_discrete(position = 'top') + 
  coord_fixed() + 
  theme(
    axis.title = element_blank(),
    axis.text.x = element_text(angle = 90, hjust = 0, vjust = 0.5))
ggsave('_figures/cor_dfcounty.png', width = 8, height = 8)

cor(df.tract %>% select(vars)) %>% 
  as.data.frame %>% 
  rownames_to_column %>% 
  pivot_longer(-rowname) %>%
  mutate(rowname = factor(rowname, levels = vars), name = factor(name, levels = rev(vars))) %>% 
  ggplot() + 
  geom_tile(aes(x = rowname, y = name, fill = value)) + 
  scale_fill_scico(palette = 'vik', midpoint = 0, direction = -1) + 
  scale_x_discrete(position = 'top') + 
  coord_fixed() + 
  theme(
    axis.title = element_blank(),
    axis.text.x = element_text(angle = 90, hjust = 0, vjust = 0.5))
ggsave('_figures/cor_dftract.png', width = 8, height = 8)

```

# run PCA algorithm

```{r}
df.pca <- df.smote

```

```{r}
vif(glm(y ~ ., data = df.pca, family = 'binomial')) %>% round(2) %>% sort(decreasing = TRUE)
plot_contribution(df.pca, plot.dim = 7)
pca.var.list <- c('pct_floodplain', 'pop_pct_floodplain', 'hu_pct_floodplain')
plot_components(df.pca, pca.var.list)
predictive_power(df.pca, pca.var.list)
df.pca <- df.pca %>% select(-pop_pct_floodplain, -pct_floodplain)

```

```{r}
vif(glm(y ~ ., data = df.pca, family = 'binomial')) %>% round(2) %>% sort(decreasing = TRUE)
plot_contribution(df.pca, plot.dim = 7)
pca.var.list <- c('sm_lag03', 'sm_lag07', 'sm_lag14', 'sm_lag30')
plot_components(df.pca, pca.var.list)
predictive_power(df.pca, pca.var.list)
df.pca <- df.pca %>% select(-sm_lag07, -sm_lag14, -sm_lag30)

cor(df.pca %>% select(-y)) %>% 
  as.data.frame %>% rownames_to_column %>% 
  pivot_longer(-rowname) %>% 
  filter(rowname != name) %>% 
  arrange(desc(abs(value))) %>% 
  mutate(pair = rep(c(1,2), nrow(.)/2)) %>% 
  filter(pair == 1) %>% select(-pair) %>% 
  filter(grepl('logprecip',rowname) & grepl('logprecip',name))
predictive_power(df.pca, c('logprecip_total', 'logprecip_max'))
df.pca <- df.pca %>% select(-logprecip_max)
pca.var.list <- c('logprecip_lag03', 'logprecip_lag07', 'logprecip_lag14', 'logprecip_lag30')
plot_components(df.pca, pca.var.list)
predictive_power(df.pca, pca.var.list)
df.pca <- df.pca %>% select(-logprecip_lag07, -logprecip_lag30)

```

```{r}
vif(glm(y ~ ., data = df.pca, family = 'binomial')) %>% round(2) %>% sort(decreasing = TRUE)
# plot_contribution(df.pca, plot.dim = 7)
pca.var.list <- c('logpop', 'loghu', 'logpopdensity', 'pct_developed')
plot_components(df.pca, pca.var.list)
predictive_power(df.pca, c('logpop', 'loghu'))
df.pca <- df.pca %>% select(-loghu)
predictive_power(df.pca, c('logpopdensity', 'pct_developed'))
df.pca <- df.pca %>% select(-pct_developed)

```

```{r}
cor(df.pca %>% select(-y)) %>%
  as.data.frame %>% rownames_to_column %>% pivot_longer(-rowname) %>% 
  filter(rowname != name) %>% 
  arrange(desc(abs(value))) %>% 
  mutate(pair = rep(c(1,2), nrow(.)/2)) %>% filter(pair == 1) %>% select(-pair) %>% 
  head
predictive_power(df.pca, c('pct_sfh', 'pct_ownocc'))
df.pca <- df.pca %>% select(-pct_sfh)
predictive_power(df.pca, c('pre1980', 'med_struct_age'))
df.pca <- df.pca %>% select(-pre1980)

```

```{r}
vif(glm(y ~ ., data = df.pca, family = 'binomial')) %>% round(2) %>% sort(decreasing = TRUE)
plot_contribution(df.pca, plot.dim = 7)
cor(df.pca %>% select(-y)) %>%
  as.data.frame %>% rownames_to_column %>% pivot_longer(-rowname) %>% 
  filter(rowname != name) %>% 
  arrange(desc(abs(value))) %>% 
  mutate(pair = rep(c(1,2), nrow(.)/2)) %>% filter(pair == 1) %>% select(-pair) %>% 
  head

```

